// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR-hGKCdRkgPjIoEHPFesxy7F5FuJ9R9Y',
    appId: '1:689730103440:web:720b2891f848aede079015',
    messagingSenderId: '689730103440',
    projectId: 'repertoire-prod-choir',
    authDomain: 'repertoire-prod-choir.firebaseapp.com',
    storageBucket: 'repertoire-prod-choir.firebasestorage.app',
    measurementId: 'G-5ZZ7102ZP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB58ujaYRW2GJt5KJtt47DywIBU5W0tH3M',
    appId: '1:689730103440:android:33f803af75be0178079015',
    messagingSenderId: '689730103440',
    projectId: 'repertoire-prod-choir',
    storageBucket: 'repertoire-prod-choir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYQbi9kV3OHf4r3AhyQYOla7dFkkPsXaw',
    appId: '1:689730103440:ios:c4c0d1ee8fae3de8079015',
    messagingSenderId: '689730103440',
    projectId: 'repertoire-prod-choir',
    storageBucket: 'repertoire-prod-choir.firebasestorage.app',
    iosBundleId: 'com.tuorg.repertoire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYQbi9kV3OHf4r3AhyQYOla7dFkkPsXaw',
    appId: '1:689730103440:ios:ebf29f582e490e73079015',
    messagingSenderId: '689730103440',
    projectId: 'repertoire-prod-choir',
    storageBucket: 'repertoire-prod-choir.firebasestorage.app',
    iosBundleId: 'com.example.tucoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR-hGKCdRkgPjIoEHPFesxy7F5FuJ9R9Y',
    appId: '1:689730103440:web:810ef395e010ee4d079015',
    messagingSenderId: '689730103440',
    projectId: 'repertoire-prod-choir',
    authDomain: 'repertoire-prod-choir.firebaseapp.com',
    storageBucket: 'repertoire-prod-choir.firebasestorage.app',
    measurementId: 'G-WJ7T7517E9',
  );
}
